### ISSUE TITLE
DL Entry+ 취약점 경고 추가 요청

### ISSUE THREAD

**Issue by EHackC** [EntryFireRun/entryExtensionsList#3]
악용 가능성 때문에 무슨 취약점인지는 안 적을 건데 취약점 있어요

**Comment by EntryFireRun** [comment]
~~귀찮아요~~ 금방 보안 패치를 할 것 같네요, 시간 지나도 패치를 안하면 수정하겠습니다

**Comment by EntryFireRun** [comment]
생각해보니 업데이트 심사 기간이 늦어질 수 있네요
